商业 内存泄漏检测工具，没有找到相关的

原文链接：https://blog.csdn.net/k1419197516/article/details/129957969，原作者： 搞IT的锋
以下是一些常用的内存泄漏检查工具：
1. Valgrind：Valgrind是一种开源的内存调试和性能分析工具，可以检测内存泄漏、使用未初始化的内存、使用已释放的内存等问题。
2. AddressSanitizer（ASan）：ASan是一种内存错误检测工具，可以检测内存泄漏、缓冲区溢出、使用未初始化的内存等问题。
3. LeakSanitizer（LSan）：LSan是一种内存泄漏检测工具，可以检测动态分配的内存是否被释放。
4. Electric Fence：Electric Fence是一种内存调试工具，可以检测内存越界、使用已释放的内存等问题。
5. Purify：Purify是一种商业化的内存泄漏检测工具，可以检测内存泄漏、使用未初始化的内存等问题。
6. Insure++：Insure++是一种商业化的内存泄漏检测工具，可以检测内存泄漏、使用未初始化的内存等问题。

转载自：https://zhuanlan.zhihu.com/p/608640068
1. Valgrind是分析Linux和Mac OS x上各种内存问题的首选工具。它使用单独的工具进行特定的内存分析：如分析和内存检查。Valgrind在Windows上不可用，
    （1-1）KCacheGrind        KCacheGrind是一款Valgrind分析结果的可视化工具。
    （1-2）Massif Visualizer  Massif Visualizer是一个数据的可视化工具。配合Valgrind工具一起使用。
    （1-3）AddressSanitizer   AddressSanitizer是一款内置在gcc 4.8和clang中内存监控工具。
2. 
二、Windows下的内存检测工具
1. Deleaker
   Deleaker是一款功能强大的内存检测工具，但要收费。 当安装成功后，会作为插件添加到QtCreaotr中，我们直接在QtCreator中使用即可：
2. VLD 可用于Qt C++开发中进行内存检测的工具：vld。
   Visual Leak Detector (VLD)是一款用于Visual c++的内存泄漏检测工具。它的特点是:可以得到内存泄漏点的调用栈，如果可以，还可以得到它所在的文件和行号;
   可以获得泄漏内存的完整数据;您可以设置内存泄漏报告的级别;它是开源和免费的。美中不足的是，只能使用vc++编译器。
3. MTuner可以获得内存使用和分配模式的情况，能给我们分析内存提供数据和数据查看窗口。该工具开源、免费。能以时间轴的方式显示和记录软件运行期间的内存行为。
4. Diagnostic 是一款免费，开源的工具，支持32/64位架构。
5. heob工具免费，开源。已经集成到QtCreator中，用于检测缓冲区溢出和内存泄漏。
6. WonderLeak 该工具收费。是一个高性能的Windows堆和句柄分配分析器。软件界面如下：

转载自：https://www.cnblogs.com/findumars/p/5353538.html，原作者：昵称： findumars
1.     ccmalloc－Linux和Solaris下对C和C++程序的简单的使用内存泄漏和malloc调试库。
2.     Dmalloc－Debug Malloc Library.
3.     Electric Fence－Linux分发版中由Bruce Perens编写的malloc()调试库。
4.     Leaky－Linux下检测内存泄漏的程序。
5.     LeakTracer－Linux、Solaris和HP-UX下跟踪和分析C++程序中的内存泄漏。
6.     MEMWATCH－由Johan Lindh编写，是一个开放源代码C语言内存错误检测工具，主要是通过gcc的precessor来进行。
7.     Valgrind－Debugging and profiling Linux programs, aiming at programs written in C and C++.
8.     KCachegrind－A visualization tool for the profiling data generated by Cachegrind and Calltree.
9.     Leak Monitor－一个Firefox扩展，能找出跟Firefox相关的泄漏类型。
10.  IE Leak Detector (Drip/IE Sieve)－Drip和IE Sieve leak detectors帮助网页开发员提升动态网页性能通过报告可避免的因为IE局限的内存泄漏。
11.  Windows Leaks Detector－探测任何Win32应用程序中的任何资源泄漏(内存，句柄等)，基于Win API调用钩子。
12.  SAP Memory Analyzer－是一款开源的JAVA内存分析软件，可用于辅助查找JAVA程序的内存泄漏，能容易找到大块内存并验证谁在一直占用它，它是基于Eclipse RCP(Rich Client Platform)，可以下载RCP的独立版本或者Eclipse的插件。
13.  DTrace－即动态跟踪Dynamic Tracing，是一款开源软件，能在Unix类似平台运行，用户能够动态检测操作系统内核和用户进程，以更精确地掌握系统的资源使用状况，提高系统性能，减少支持成本，并进行有效的调节。
14.  IBM Rational PurifyPlus－帮助开发人员查明C/C++、托管.NET、Java和VB6代码中的性能和可靠性错误。PurifyPlus 将内存错误和泄漏检测、应用程序性能描述、代码覆盖分析等功能组合在一个单一、完整的工具包中。
15.  Parasoft Insure++－针对C/C++应用的运行时错误自动检测工具，它能够自动监测C/C++程序，发现其中存在着的内存破坏、内存泄漏、指针错误和I/O等错误。并通过使用一系列独特的技术（SCI技术和变异测试等），彻底的检查和测试我们的代码，精确定位错误的准确位置并给出详细的诊断信息。能作为Microsoft Visual C++的一个插件运行。
16.  Compuware DevPartner for Visual C++ BoundsChecker Suite－为C++开发者设计的运行错误检测和调试工具软件。作为Microsoft Visual Studio和C++ 6.0的一个插件运行。
17.  Electric Software GlowCode－包括内存泄漏检查，code profiler，函数调用跟踪等功能。给C++和.Net开发者提供完整的错误诊断，和运行时性能分析工具包。
18.  Compuware DevPartner Java Edition－包含Java内存检测,代码覆盖率测试,代码性能测试,线程死锁,分布式应用等几大功能模块。
19.  Quest JProbe－分析Java的内存泄漏。
20.  ej-technologies JProfiler－一个全功能的Java剖析工具，专用于分析J2SE和J2EE应用程序。它把CPU、执行绪和内存的剖析组合在一个强大的应用中。JProfiler可提供许多IDE整合和应用服务器整合用途。JProfiler直觉式的GUI让你可以找到效能瓶颈、抓出内存泄漏、并解决执行绪的问题。4.3.2注册码：A-G666#76114F-1olm9mv1i5uuly#0126
21.  BEA JRockit－用来诊断Java内存泄漏并指出根本原因，专门针对Intel平台并得到优化，能在Intel硬件上获得最高的性能。
22.  SciTech Software AB .NET Memory Profiler－找到内存泄漏并优化内存使用针对C#，VB.Net，或其它.Net程序。
23.  YourKit .NET & Java Profiler－业界领先的Java和.NET程序性能分析工具。
24.  AutomatedQA AQTime－AutomatedQA的获奖产品performance profiling和memory debugging工具集的下一代替换产品，支持Microsoft, Borland, Intel, Compaq 和 GNU编译器。可以为.NET和Windows程序生成全面细致的报告，从而帮助您轻松隔离并排除代码中含有的性能问题和内存/资源泄露问题。支持.Net 1.0,1.1,2.0,3.0和Windows 32/64位应用程序。
